### ISSUE TITLE
Support Powerpoint

### ISSUE THREAD

**Issue by Immortalin** [phiresky/ripgrep-all#124] opened 2022-03-03 19:06 UTC
https://www.loc.gov/preservation/digital/formats/fdd/fdd000399.shtml

**Comment by Mstrodl** [comment] 2022-10-13 16:05
I've been using this:
```
soffice --headless --convert-to pdf *.ppt *.pptx && rm *.ppt *.pptx
```

**Comment by lafrenierejm** [comment] 2023-11-22 16:51
This seems like a duplicate of <https://github.com/phiresky/ripgrep-all/issues/69>.

**Comment by Konfekt** [comment] 2024-01-10 19:12
Might https://github.com/phiresky/ripgrep-all/discussions/199 be of help?

**Comment by phiresky** [comment] 2024-01-16 00:12
Please see @Konfekt s custom adapter #199

**Closed by phiresky** 2024-01-16 00:12 UTC
