### ISSUE TITLE
docs(adapters): third-party adapters commands

### ISSUE THREAD

**Issue by Kristinita** [phiresky/ripgrep-all#53] opened 2020-05-20 13:50 UTC
### 1. Summary

It would be nice, if ripgrep-all documentation will have information, which commands of [**available third-party adapters**](https://github.com/phiresky/ripgrep-all#available-adapters) ripgrep-all run in the process of finding text in books.

### 2. Example

For example, for PDF ripgrep-all [**uses**](https://github.com/phiresky/ripgrep-all/issues/44#issuecomment-629836946) command `pdftotext -layout <BookName>.pdf`. It would be nice, if users will know commands for another file types.

#### 3.1. Common cause

More debugging information.

#### 3.2. Details

Imagine that ripgrep-all user get unexpected result. If the user knows the adapter commands, he can determine, where the problem — in ripgrep-all or in third-party tools → user can continue debugging with more of important data.

Thanks.

**Comment by phiresky** [comment] 2020-05-20 14:01
This is not really possible in general, since except for the adapters that subclass SpawningFileAdapter, the adapters use internal methods to extract the data instead of calling external tools. You can get some more debug information by running rga or rga-preproc with `env RUST_LOG=debug`

Example:

```
$ RUST_LOG=debug rga-preproc -- --rga-no-cache exampledir/short.pdf
[2020-05-20T13:58:02Z DEBUG ripgrep_all::args] RGA_CONFIG={"no_cache":true}
[2020-05-20T13:58:02Z DEBUG ripgrep_all::adapters] Chosen adapters: ffmpeg,pandoc,poppler,zip,decompress,tar,sqlite
[2020-05-20T13:58:02Z DEBUG ripgrep_all::preproc] depth: 0
[2020-05-20T13:58:02Z DEBUG ripgrep_all::preproc] path_hint: "/home/tehdog/data/dev/2019/ripgrep-all/exampledir/short.pdf"
[2020-05-20T13:58:02Z DEBUG ripgrep_all::preproc] chose adapter 'poppler' because of matcher Fast(FileExtension("pdf"))
adapter: poppler
[2020-05-20T13:58:02Z DEBUG ripgrep_all::preproc] adapting...
[2020-05-20T13:58:02Z DEBUG ripgrep_all::adapters::spawning] executing "pdftotext" "-" "-"
Page 1: hello world
Page 1: this is just a test.
Page 1: 
Page 1: 1
Page 1: 
```

**Comment by phiresky** [comment] 2020-05-20 14:02
I added a bit more info to the debug log in 5d97c2a

**Comment by phiresky** [comment] 2020-06-09 11:38
Closing as dupe of #60 and #63

**Closed by phiresky** 2020-06-09 11:38 UTC
