### ISSUE TITLE
Why can't I search the contents of PDF files?

### ISSUE THREAD

**Issue by zhl111** [phiresky/ripgrep-all#142] opened 2022-08-16 18:37 UTC
I don't know much about programming, please tell me how to do it
1.![image](https://user-images.githubusercontent.com/29135984/184953687-f5f6cdf7-d23d-4356-bde2-8df04348ca55.png)
2.
![image](https://user-images.githubusercontent.com/29135984/185144722-b84de5ce-a53b-4659-995e-dfe86dac812c.png)

**Comment by lafrenierejm** [comment] 2023-11-20 22:43
It looks like `rga` is finding matching lines in your PDF, but Windows Terminal is failing to print the matches because they contain strings that are not valid UTF-8. AFAIK `rga` will transparently re-encode UTF-16 to UTF-8, so there are three potential points of failure:
1. `rga` _is_ returning valid UTF-8, and Windows Terminal's detection/rendering is broken.
2. `rga`'s conversion to UTF-8 is broken in such a way that the conversion itself is resulting in garbled output.
3. The original doc contained some number of byte sequences that `rga` could _not_ convert to UTF-8, `rga` just returned those sequences verbatim in addition to whatever valid UTF-8 it could return, and Windows Terminal is complaining that there were _any_ byte strings that weren't valid UTF-8.

To try to rule out the first possibility, @zhl111 could you provide the version of Windows Terminal that you're running?

**Comment by lafrenierejm** [comment] 2023-11-22 16:55
I _suspect_ that Unicode normalization as described in https://github.com/phiresky/ripgrep-all/issues/26 would fix this.

**Comment by phiresky** [comment] 2024-01-16 00:31
I'll assume this is a dupe of #47

**Closed by phiresky** 2024-01-16 00:31 UTC
