### ISSUE TITLE
Warning: found multiple adapters for dvt_build.log.xz-9.xz

### ISSUE THREAD

**Issue by gcflymoto** [phiresky/ripgrep-all#167] opened 2023-05-27 00:47 UTC
Hi is it expected for rga to run the decompressor twice if .xz is twice in the file name? Or should it be more strict and only do that for <filename>.xz.xz ??

dvt_build.log.xz-9.xz: preprocessor command failed: '"rga-preproc" "dvt_build.log.xz-9.xz"': 
-------------------------------------------------------------------------------
Warning: found multiple adapters for dvt_build.log.xz-9.xz:
 - decompress
 - decompress
dvt_build.log.xz-9.xz adapter: decompress
Error: during preprocessing

Caused by:
    0: run_adapter(dvt_build.log.xz-9.xz)
    1: Rusqlite("database is locked")
    2: database is locked
    3: Error code 5: The database file is locked

**Comment by phiresky** [comment] 2023-06-04 14:59
Could you attach the file and send the output of `rga --version`?

The "database is locked" error is potentially unrelated to the duplictae adapter warning. I can't reproduce the duplicate adapter warning though.

**Comment by phiresky** [comment] 2024-01-15 23:38
Duplicate of #188

**Closed by phiresky** 2024-01-15 23:38 UTC
