### ISSUE TITLE
installed on mint 19.1 (ubuntu 18.04) error reading .odt files  - ./file.odt: preprocessor command failed: '"rga-preproc" "./file.odt"':  ------------------------------------------------------------------------------- adapter: pandoc pandoc: Cannot read archive from stdin CallStack (from HasCallStack):   error, called at pandoc.hs:1386:22 in main:Main Error: Broken pipe (os error 32) -------------------------------------------------------------------------------

### ISSUE THREAD

**Issue by andreampiovesana** [phiresky/ripgrep-all#23] opened 2019-07-09 17:18 UTC

**Comment by phiresky** [comment] 2019-07-09 18:44
Can you send the corresponding odt file?

**Comment by andreampiovesana** [comment] 2019-07-10 13:40
all made by libreoffice

Andrea Piovesana linux counter #601470 Linux Mint 19.1www.pnlug.it



Il giorno mar 9 lug 2019 alle ore 20:44 phiresky <notifications@github.com>
ha scritto:

**Comment by phiresky** [comment] 2019-07-10 20:19
Cannot reproduce with a simple document made from libreoffice - maybe your pandoc version is too old? I would need a odt file where this happens to verify

**Comment by mizuno-as** [comment] 2019-07-17 09:08
It was able to reproduce with the "exampledir/demo/hello.odt".

The version is as follows:
  Ubuntu 18.04.2
  pandoc 1.19.2.4
  ripgrep-all 0.9.2

```
$ rga 'hello' demo/
demo/hello.odt: preprocessor command failed: '"rga-preproc" "demo/hello.odt"': 
-------------------------------------------------------------------------------
adapter: pandoc
pandoc: Cannot read archive from stdin
CallStack (from HasCallStack):
  error, called at pandoc.hs:1386:22 in main:Main
Error: subprocess failed: ExitStatus(ExitStatus(256))
```

but, Ubuntu 19.04 (pandoc 2.2.1) is works fine.
I think that the version of pandoc is old.

thanks.

**Comment by phiresky** [comment] 2019-07-17 19:12
Thanks for the additional info. I'll close this since I don't want to support older versions. Maybe I should try adding version checks..

**Closed by phiresky** 2019-07-17 19:12 UTC

**Comment by alexander-winkler** [comment] 2020-01-02 14:39
I've got pandoc 2.7.3 on my machine (Linux Mint 19.1 Tessa) and I get the same error when I try apply ripgrep (ripgrep-all 0.9.3) on *.odt files.

```
rga 'test' test.odt 
test.odt: preprocessor command failed: '"rga-preproc" "test.odt"': 
-------------------------------------------------------------------------------
adapter: pandoc
pandoc: Cannot read archive from stdin
CallStack (from HasCallStack):
  error, called at pandoc.hs:1386:22 in main:Main
Error: subprocess failed: ExitStatus(ExitStatus(256))
-------------------------------------------------------------------------------
```

**Comment by phiresky** [comment] 2020-01-02 14:41
Your pandoc is outdated. If you think you have current pandoc you probably have multiple versions installed.

**Comment by alexander-winkler** [comment] 2020-01-02 14:54
You were right! I've doublechecked, the pandoc in /usr/bin/ was outdated. Thanks!
