### ISSUE TITLE
Why the latest release doesn't include Windows version?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [phiresky/ripgrep-all#41] opened 2020-05-05 05:07 UTC

**Comment by phiresky** [comment] 2020-05-15 15:31
The issue is that travis-ci, which I rely on to build windows binaries, has changed something on their side so now the Windows builds are failing. I've tried to fix this in a few different ways, but haven't gotten it to work so far and it's annoying to deal with so I'm not terribly motivated to spend more time on it.

Not much has changed in 0.9.5 so far though, so for now just use https://github.com/phiresky/ripgrep-all/releases/tag/0.9.3

**Comment by Kristinita** [comment] 2020-05-18 12:44
**Type: Question** ❓

### 1. Question

@phiresky, did you try for Windows builds [**AppVeyor**](https://www.appveyor.com/) or another alternatives (as [**Circle CI**](https://circleci.com/)) instead of Travis CI?

### 2. Argumentation

#### 2.1. AppVeyor pros

1. Travis CI Windows early release dated by [**11 October 2018**](https://blog.travis-ci.com/2018-10-11-windows-early-release).
1. AppVeyor [**founded in 2011**](https://www.appveyor.com/about/) and [**before 6 March 2018**](https://www.appveyor.com/blog/2018/03/06/appveyor-for-linux/) support solely Windows builds.

AppVeyor developers more time worked for Windows builds.

#### 2.2. AppVeyor minuses

[**Some encoding problems**](https://github.com/appveyor/ci/issues/created_by/Kristinita).

### 3. Details

You can see [**my commented `appveyor.yml`**](https://github.com/Kristinita/KristinitaPelican/blob/master/appveyor.yml) file to be ready for AppVeyor pitfalls.

Thanks.

**Comment by phiresky** [comment] 2020-05-18 12:57
Thanks for the suggestion.

I'm changing to github actions. there windows builds work fine. 

It's currently in https://github.com/phiresky/rga-windows-test (see releases), i'll merge it soon.

**Comment by phiresky** [comment] 2020-05-19 10:17
fixed in 0.9.6 https://github.com/phiresky/ripgrep-all/releases

**Closed by phiresky** 2020-05-19 10:17 UTC
