### ISSUE TITLE
Error: Unsupported Zip archive: The file length is not available in the local header

### ISSUE THREAD

**Issue by asanchez75** [phiresky/ripgrep-all#112] opened 2021-08-13 08:45 UTC
Hello

Thanks for this amazing tool!
I have an issue to report. I got this error in Ubuntu 20.04.2 LTS

```
-------------------------------------------------------------------------------
./Tourism_sample.csv.zip: preprocessor command failed: '"/usr/local/bin/rga-preproc" "./Tourism_sample.csv.zip"': 
-------------------------------------------------------------------------------
adapter: zip
Error: Unsupported Zip archive: The file length is not available in the local header
```

```
-------------------------------------------------------------------------------
./ojs-3.3.0-6.tar.gz: preprocessor command failed: '"/usr/local/bin/rga-preproc" "./ojs-3.3.0-6.tar.gz"': 
-------------------------------------------------------------------------------
adapter: decompress
adapter: tar
Error: invalid gzip header

```
Just in case, I run before

```
apt install ripgrep pandoc poppler-utils ffmpeg
```

Thanks

**Comment by phiresky** [comment] 2021-08-13 09:40
Yep, this is a known issue. Should be fixed for most cases when https://github.com/phiresky/ripgrep-all/issues/82 is fixed.

**Comment by phiresky** [comment] 2021-08-13 09:42
Closing as a duplicate of https://github.com/phiresky/ripgrep-all/issues/86

**Closed by phiresky** 2021-08-13 09:42 UTC
